# Generated by Django 6.0.5 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedopportunity',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
