# Generated by Django 4.2.30 on 2026-05-21 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_fellowship_hackathon_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='saved_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
