# Generated by Django 4.2.30 on 2026-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(default='saved', max_length=20),
        ),
    ]
