# Generated by Django 4.2.30 on 2026-05-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_opportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
