# Generated by Django 4.2.30 on 2026-05-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='minimum_cgpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
    ]
