# Generated by Django 4.2.30 on 2026-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentprofile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume_link',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='difficulty_level',
            field=models.CharField(default='Beginner', max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='link',
            field=models.URLField(default='python, django'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='minimum_cgpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skills_required',
            field=models.TextField(default='python, django'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
