# Generated by Django 4.2.30 on 2026-05-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_opportunity_ai_category_opportunity_minimum_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowship',
            name='required_skills',
            field=models.CharField(default='', max_length=300),
        ),
    ]
