# Generated by Django 4.2.30 on 2026-05-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fellowship_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='required_skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
