# Generated by Django 4.2.30 on 2026-05-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_scholarship_required_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='required_skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='organizer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
